name: Docker

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-image:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:  # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
      - uses: docker/build-push-action@v2.6.1
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: ./app # optional
      